#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BluetoothSheduler.Resource", IsApplication=true)]

namespace BluetoothSheduler
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Library.Resource.Attribute.checkText = global::BluetoothSheduler.Resource.Attribute.checkText;
			global::Library.Resource.Color.blue_color = global::BluetoothSheduler.Resource.Color.blue_color;
			global::Library.Resource.Color.gray_back = global::BluetoothSheduler.Resource.Color.gray_back;
			global::Library.Resource.Color.gray_color = global::BluetoothSheduler.Resource.Color.gray_color;
			global::Library.Resource.Color.gray_text = global::BluetoothSheduler.Resource.Color.gray_text;
			global::Library.Resource.Color.green_color = global::BluetoothSheduler.Resource.Color.green_color;
			global::Library.Resource.Color.red_color = global::BluetoothSheduler.Resource.Color.red_color;
			global::Library.Resource.Drawable.rounded_background_selected = global::BluetoothSheduler.Resource.Drawable.rounded_background_selected;
			global::Library.Resource.Drawable.rounded_background_unselected = global::BluetoothSheduler.Resource.Drawable.rounded_background_unselected;
			global::Library.Resource.String.ApplicationName = global::BluetoothSheduler.Resource.String.ApplicationName;
			global::Library.Resource.String.Hello = global::BluetoothSheduler.Resource.String.Hello;
			global::Library.Resource.Styleable.CheckLinear = global::BluetoothSheduler.Resource.Styleable.CheckLinear;
			global::Library.Resource.Styleable.CheckLinear_checkText = global::BluetoothSheduler.Resource.Styleable.CheckLinear_checkText;
			global::Model.Resource.String.ApplicationName = global::BluetoothSheduler.Resource.String.ApplicationName;
			global::Model.Resource.String.Hello = global::BluetoothSheduler.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int checkText = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int blue_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int gray_back = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int gray_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int gray_text = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int green_color = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int red_color = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bluetooth = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_blue_border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int check_box_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int rounded_background_selected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rounded_background_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splashscreen = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int btn_end_time = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int btn_save = 2131165203;
			
			// aapt resource value: 0x7f07000e
			public const int btn_start_time = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int cl_friday = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int cl_monday = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int cl_saturday = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int cl_sunday = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int cl_thursday = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int cl_tuesday = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int cl_wednesday = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int content_timer = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int linearLayout2 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout3 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout4 = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int main = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int scrollView1 = 2131165185;
			
			// aapt resource value: 0x7f070010
			public const int tv_end = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int tv_fake = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int tv_next_pool = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public const int tv_start = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int timer_layout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int CheckBox = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Base = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int btn_style = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int txt_style = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CheckLinear = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int CheckLinear_checkText = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
